# Generated by Django 4.1 on 2024-06-28 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_alter_review_game"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"managed": False},
        ),
    ]
