# Generated by Django 4.1 on 2024-07-01 02:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_alter_review_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="review",
            table="reviewscore",
        ),
    ]
