# Generated by Django 4.1 on 2024-07-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_alter_review_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("essay", models.TextField()),
            ],
            options={
                "db_table": "userscore",
                "managed": False,
            },
        ),
    ]
