# Generated by Django 4.1 on 2024-07-01 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0006_alter_review_options_alter_userreview_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="userreview",
            options={"managed": False},
        ),
    ]
